### ISSUE TITLE
Bulk unpublishing of Offerings

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/wirrc.org#1]
Provide a mechanism for Offerings to be unpublished in bulk at the close of an academic session. This is likely as simple as enabling Administration Views and adding a filter for academic session.

**Comment by GaryRidgway** [comment]
This should be completed with https://github.com/ITS-UofIowa/wirrc.org/pull/3/commits/62bcf198d2dfc643b6a04f865446a7ab2a71f980 https://github.com/ITS-UofIowa/wirrc.org/pull/3/commits/190f7e43f9300291e36ba5ce92aa31b18738c60b and https://github.com/ITS-UofIowa/wirrc.org/pull/3/commits/0a11e3560ae7a0b4f67c61a5d980cd2f585708d3
