### ISSUE TITLE
Default vaule of academic session for Offerings

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/wirrc.org#2]
Adjust the entry of the academic sessions so that it defaults to a particular academic session (which will change 2-4 times a year). Ideally, users with the webmaster role should be able to configure what the default value is at any time.

**Comment by GaryRidgway** [comment]
Should be completed in https://github.com/ITS-UofIowa/wirrc.org/commit/737d4dcfa8c0b0080987cd024f6253ea70540a54

Will close when pushed to prod
